In [1]:
#import Library yang Diperlukan
import pandas as pd
import numpy as np
import time

In [17]:
#membaca data
penjualan = pd.read_csv('penjualan,.csv')

In [19]:
penjualan.shape

(20, 11)

In [18]:
#menampilkan 5 data teratas
penjualan.head()

Pembeli  Gula  Kopi  Teh  Aqua  Garam  Minyak  Beras  Odol Gigi  \
0     GUNA     1     1    1     1      0       0      1          0   
1    MULYA     1     1    1     0      0       0      0          0   
2  SUDARMA     0     0    1     1      1       1      1          0   
3     YASA     1     0    0     1      1       0      0          1   
4  ZABDIEL     0     1    0     0      1       1      1          1   

   Sikat Gigi  Tisu  
0           1     0  
1           0     1  
2           1     0  
3           0     1  
4           1     0

In [21]:
#menampilkan 5 data terakhir
penjualan.tail()

Pembeli  Gula  Kopi  Teh  Aqua  Garam  Minyak  Beras  Odol Gigi  \
15     ADIT     1     1    0     0      0       1      1          1   
16  PURNOMO     0     0    0     0      0       0      0          1   
17    SURYA     1     0    1     0      1       1      1          0   
18   WIJAYA     1     1    1     1      1       0      0          1   
19   KUSUMA     1     0    0     1      0       1      1          0   

    Sikat Gigi  Tisu  
15           1     1  
16           1     1  
17           1     0  
18           0     0  
19           1     1

In [39]:
def drop_data():
    print("Proses drop kolom yg tidak diperlukan")
    global penjualan
    penjualan = penjualan.drop(columns=['Pembeli'])
    time.sleep(10)
    print("Drop Berhasil")
    time.sleep(5)
    print("Proses selesai")

In [42]:
drop_data()

Proses drop kolom yg tidak diperlukan
Drop Berhasil
Proses selesai


In [43]:
penjualan

Gula  Kopi  Teh  Aqua  Garam  Minyak  Beras  Odol Gigi  Sikat Gigi  Tisu
0      1     1    1     1      0       0      1          0           1     0
1      1     1    1     0      0       0      0          0           0     1
2      0     0    1     1      1       1      1          0           1     0
3      1     0    0     1      1       0      0          1           0     1
4      0     1    0     0      1       1      1          1           1     0
5      1     1    1     1      1       0      0          1           0     1
6      0     1    0     0      0       1      1          1           1     0
7      1     0    0     1      0       0      1          0           0     1
8      1     1    1     0      1       1      0          1           0     0
9      0     0    1     1      0       1      1          0           1     1
10     1     1    0     1      1       0      0          1           1     0
11     0     0    0     1      0       1      1          0           0     1
12     0     0    1     0      1       1      0          1           0     1
13     1     1    0     0      0       0      1          0           0     0
14     0     1    1     1      1       0      0          1           1     0
15     1     1    0     0      0       1      1          1           1     1
16     0     0    0     0      0       0      0          1           1     1
17     1     0    1     0      1       1      1          0           1     0
18     1     1    1     1      1       0      0          1           0     0
19     1     0    0     1      0       1      1          0           1     1

In [44]:
#melihat atribut dari data
penjualan.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Gula        20 non-null     int64
 1   Kopi        20 non-null     int64
 2   Teh         20 non-null     int64
 3   Aqua        20 non-null     int64
 4   Garam       20 non-null     int64
 5   Minyak      20 non-null     int64
 6   Beras       20 non-null     int64
 7   Odol Gigi   20 non-null     int64
 8   Sikat Gigi  20 non-null     int64
 9   Tisu        20 non-null     int64
dtypes: int64(10)
memory usage: 1.7 KB


TAHAPAN KLASIFIKASI MENGGUNAKAN NAIVE BAYES

In [45]:
# import algoritma naive bayes
from sklearn.naive_bayes import GaussianNB

In [46]:
#import model gaussian
modelnb = GaussianNB()

In [47]:
#memuat data variabel independen kedalam variabel x
x = penjualan.drop(["Gula"],axis=1)
print(x)

    Kopi  Teh  Aqua  Garam  Minyak  Beras  Odol Gigi  Sikat Gigi  Tisu
0      1    1     1      0       0      1          0           1     0
1      1    1     0      0       0      0          0           0     1
2      0    1     1      1       1      1          0           1     0
3      0    0     1      1       0      0          1           0     1
4      1    0     0      1       1      1          1           1     0
5      1    1     1      1       0      0          1           0     1
6      1    0     0      0       1      1          1           1     0
7      0    0     1      0       0      1          0           0     1
8      1    1     0      1       1      0          1           0     0
9      0    1     1      0       1      1          0           1     1
10     1    0     1      1       0      0          1           1     0
11     0    0     1      0       1      1          0           0     1
12     0    1     0      1       1      0          1           0     1
13    

In [48]:
#memuat data variabel dependen, yaitu variabel Gula kedalam variabel x
y= penjualan["Gula"]
print(y)

0     1
1     1
2     0
3     1
4     0
5     1
6     0
7     1
8     1
9     0
10    1
11    0
12    0
13    1
14    0
15    1
16    0
17    1
18    1
19    1
Name: Gula, dtype: int64


In [49]:
# import library machine learning sklearn
from sklearn.model_selection import train_test_split

In [50]:
# meload data x dan data y kedalam data training dan juga data test
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=123)

In [51]:
x_train.head(5)

Kopi  Teh  Aqua  Garam  Minyak  Beras  Odol Gigi  Sikat Gigi  Tisu
8      1    1     0      1       1      0          1           0     0
7      0    0     1      0       0      1          0           0     1
19     0    0     1      0       1      1          0           1     1
12     0    1     0      1       1      0          1           0     1
0      1    1     1      0       0      1          0           1     0

In [52]:
x_train.shape

(16, 9)

In [53]:
y_train.head(5)

8     1
7     1
19    1
12    0
0     1
Name: Gula, dtype: int64

In [54]:
y_train.shape

(16,)

In [55]:
x_test.head(5)

Kopi  Teh  Aqua  Garam  Minyak  Beras  Odol Gigi  Sikat Gigi  Tisu
14     1    1     1      1       0      0          1           1     0
5      1    1     1      1       0      0          1           0     1
4      1    0     0      1       1      1          1           1     0
17     0    1     0      1       1      1          0           1     0

In [56]:
x_test.shape

(4, 9)

In [58]:
nbtrain = modelnb.fit(x_train, y_train)
nbtrain.class_count_


array([ 6., 10.])

In [59]:
#prediksi
y_pred = nbtrain.predict(x_test)
y_pred

array([1, 1, 1, 0], dtype=int64)

In [60]:
probabilitas = nbtrain.predict_proba(x_test)
probabilitas.shape

(4, 2)

In [61]:
#probabilitas dari data test
probabilitas

array([[0.0055878 , 0.9944122 ],
       [0.00369073, 0.99630927],
       [0.25366036, 0.74633964],
       [0.93642583, 0.06357417]])